# 数据科学/数据处理的流程

## Project name: ds_proj_pd01

文件来源： 此文件出自Python For Beginner学习社群。

作者： 闫小峰

Last Update: 2025-09-17

## 数据处理通用框架/流程模板

[0. 业务理解 Understanding](#0) 

[1. 数据获取和理解 ](#1)
- 数据分析环境设置 Set Up Environment
- 数据获取/采样
- 数据探索  
  - 熟悉数据属性
  - 数据体检： Sanity Checking 

[2. 预处理 Data Preparation](#2)  
- 数据清理  Data Cleaning 
- 数据准备，转换和调整


[3. 数据分析和挖掘 Data Analysis / Data  Mining](#3)
- 传统（经典）数据分析： 
  - 统计学方法 
  - 建模： 业务分析模型
- 机器学习 Machine Learning: 
  - 模型构建: 训练-测试-调试， 
  - 模型预测
- AI增强/辅助型数据分析和开发
  - LLM

[4. 模型评估  Model Evaluation ](#4)


[5. 业务理解/知识深化和提升](#5)
- 数据处理流程自动化 Pipelines
- X by Data Based/Data Driven
   -  Decision Making
   -  Story Line
   -  逻辑论证
   -  发现规律 etc

# 0.业务理解Understanding

- 目标和需求分析：
  - 目的：玩转Pandas！
    - 岗位基本操作训练：学习+练习Pandas基础结构
    - 熟悉使用Pandas读取和输出各种类型的数据（Text，Markdown，HTML，JSON，CSV，XLSX，URL）
    - 敲黑板：重点玩转Pandas的索引操作
    - 学习数据清理的技巧，了解数据清理的灵活度
- 操作执行战术分析：
  - 阶段性要求：
    - 能够实现数据读取自由
    - 进阶：Excel表格的选择读取（职场中的痛点）
    - 没有涵盖：网页爬虫爬取数据
    - 能够灵活处理缺失值和异常值

  - 数据分析需要的方法
  
- 业务理解
  - 暂无

# 1. 数据获取和理解 Get Data & Data Understanding <a id="1"></a>

### 1.1. 数据处理环境设置 Set Up Environment <a id="1.1"></a>

In [9]:
# import modules for data science 
import numpy as np
import pandas as pd

#import module for plotting
import matplotlib.pyplot as plt 
#import rcParams um chinesische Texte richtig in Matplotlib anzuzeigen
from matplotlib import rcParams
# Setze die chin. Schriftart für den Titel, die in Matpolotlib angezeigt werden kann
rcParams['font.family'] = 'SimHei'  # oder 'Microsoft YaHei'

import warnings
warnings.filterwarnings('ignore') #to suppress warning messages


#import pybds_lib as pds

%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 1.2.数据获取

### 1.2.1. Pandas读取数据方法总结


Pandas官网不同数据类型的读取存储方法[1]

Reference：  
[1]: https://pandas.pydata.org/docs/reference/io.html

#### 1.2.1. Pandas读取Text数据方法


读取以 txt格式保存的表格数据可以使用：  
pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='\t',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定txt中的分割符. tab: '\t'
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [ ]:
try:
    # Try 'latin-1' (ISO-8859-1), a common fallback for text files
    df_list = pd.read_csv('b03_data/contact_person.txt', sep=" ",encoding='latin-1',header=0)
    print("Successfully read with latin-1 encoding.")
except UnicodeDecodeError:
    print("Could not decode with common encodings. Please inspect the file.")

df_list.head()

Successfully read with latin-1 encoding.

     name surname         dob   department
0  George   Brown  12/02/1993  Engineering
1  Andrew   Black  15/04/1975           HR
2   Maria   Green  12/02/1989  Engineering
3   Helen     Fox  21/10/2000    Marketing
4     Joe     Xiu  10/11/1998  Engineering

#### 1.2.2. Pandas读取Markdown数据方法

读取md格式中的表格的概率较小，更常用的场景是将处理好的数据写入Markdown文件中的表格。

pd.to_markdown()方法

#### 1.2.3. Pandas读取HTML数据方法

pd.read_html()方法
- 只能读取网页中的表格(即<table>标签内的数据)    

pd.read_html(io, *[, match, flavor, header, ...])  - options

参数说明：  
- io: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接.注意：网址不接受https
- match: 字符串，正则表达式
- flavor：解释器。默认“lxml”
- header：整数，指定列名所在的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。

In [ ]:
import urllib.request

url = 'http://en.wikipedia.org/wiki/2008_Summer_Olympics'
headers = {'User-Agent': 'Mozilla/5.0'}
req = urllib.request.Request(url, headers=headers)   #return a request object

# turn request object into file like object or string, in oder to read it with pd.read_html
with urllib.request.urlopen(req) as response:
    html = response.read()

medal_table = pd.read_html(html, match='2008 Summer Olympics medal table')

print(medal_table)

[                   Rank                  NOC  Gold  Silver  Bronze  Total
0                     1              China*‡    48      22      30    100
1                     2       United States‡    36      39      37    112
2                     3              Russia‡    24      13      23     60
3                     4       Great Britain‡    19      13      19     51
4                     5             Germany‡    16      11      14     41
5                     6            Australia    14      15      17     46
6                     7         South Korea‡    13      11       8     32
7                     8               Japan‡     9       8       8     25
8                     9               Italy‡     8       9      10     27
9                    10              France‡     7      16      20     43
10                11–87       Remaining NOCs   108     146     167    421
11  Totals (87 entries)  Totals (87 entries)   302     303     353    958]

In [12]:
#url = 'http://en.wikipedia.org/wiki/2020_Summer_Olympics'
url = r"file:///C:/Users/yax3si/Documents/my_python/pythonlearning/02_python_ds/mydocs/ds_project_pd01/data/2008%20Summer%20Olympics%20-%20Wikipedia.htm"
# Read all tables from the page
tables = pd.read_html(url)

# Find the medal table by matching its title
for table in tables:
    if 'Nation' in table.columns or 'NOC' in table.columns:
        medal_table = table
        break

# Display the medal table
medal_table.head()

  Rank             NOC  Gold  Silver  Bronze  Total
0    1         China*‡    48      22      30    100
1    2  United States‡    36      39      37    112
2    3         Russia‡    24      13      23     60
3    4  Great Britain‡    19      13      19     51
4    5        Germany‡    16      11      14     41

#### 1.2.4. Pandas读取JSON数据方法

待补充完善！

#### 1.2.5. Pandas读取CSV数据方法

pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定CSV中的分割符
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [ ]:
#df=pd.read_csv('data.csv')          # 如果文件与代码文件在同一目录下
df=pd.read_csv('b03_data/b03_births.csv',sep=',')  # 指定目录
# 使用URL

df.head()

   year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

#### 1.2.6. Pandas读取Excel Table数据方法

pd.read_excel() - Options

>**pandas.`read_excel`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;io,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sheet_name=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;usecols=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nrows=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;true_values=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skiprows=None，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skipfooter=0，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;converters=None,<br> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dtype=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)

参数说明：
- io： 直接使用pd.read_excel(r"文件路径")，默认读取第一个sheet的全部数据。 支持str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
- sheet_name：可选（str, int, list, None, default 0）
  - str: 字符串用于引用的sheet的名称(如果有特定名称)
  - int: 整数用于引用的sheet的隐性索引（从0开始）
  - list：整数和字符串组成的列表，读取后的数据类型是OrderedDict,将列表指定的sheet的数据合并到了一个list中
  - None：表示引用所有sheet （相当于=list（all）的结果）
  - 0： 默认第一个sheet
- header: 表示用第几行作为表头，可选（int, list of int, default 0）
  - 0： 默认，即第一行为表头 
  - int: 跳选第int+1行为表头，前面行数据就被忽略了。行数从0开始
  - [int]：选择列表int指定行的数据作为表头。可用于读取合并行数据做表头
  - None: 不用源表头
- usecols:可选(int, str, list-like, or callable default None)
  - None：默认值，解析所有列。
  - str： 表示Excel列字母。列范围的逗号分隔列表（例如“ A：E”或“ A，C，E：F”）。`范围全闭`。
  - int: 解析到第几列。`对应隐性列索引，从0开始，但是范围全闭（容易让人抓狂的地方）`。 如usecols=3: 选0，1，2，3共4列数据
  - int列表: 解析int对应的那几列。
- index_col：指定列为索引列，可选（int, list of int, default None）
  - 默认为None，即隐性的行作DataFrame的行标签。
  - int: 指定第几列为索引列. 从0开始。
  - list of int：选择列表中的整数列为索引列（多重列索引）
- nrows：（int, default None），指定需要读取前多少行，通常用于较大的数据文件中。注意：从header行下一行开始算！
  - 默认为None
  - int：nrows=3 读取前三行
- skiprows：跳过指定的行，可选（int，list like）
  - int: 跳过前int行=从int+1行开始读取
  - [int]：skiprows=[1,3,5] 跳过第1,3,5行
- dtype: 指定读入的列的数据类型。可选（Type name or dict of column -> type, default None）
  - 默认为None，也就是不改变数据类型
  - 指定列的类型名称或字典。
  - 场景：作用强大，强制限制数据类型，避免后续处理出现意外。如原始字符串数字被当成数值进行运算。可结合df.info先查看各列数据类型是否合乎要求

In [ ]:
# 最简单方法： Excel文件无脑读取
df = pd.read_excel("data/simple_tables.xlsx")
df.head()

In [ ]:
# 通常还需要细选某个区域的数据，需要指定行列索引
#
df = pd.read_excel("data/simple_tables.xlsx", header=1, usecols="A:M", nrows=7)
df.head(10)

In [ ]:
# 复杂的Excel文件（比如多个sheet），可以先获取一些基本信息
# 读取sheet名称
df = pd.ExcelFile("data/complex_tables.xlsx")
df.sheet_names

In [ ]:
# 面对复杂的Excel文件（比如多个sheet），需要指定更多参数
#
df = pd.read_excel("data/complex_tables.xlsx", sheet_name='Sheet 1', header=9, usecols="A,B,D:H", nrows=19)
df.head(10)

In [ ]:
df_complex = pd.read_excel("data/complex_tables.xlsx", sheet_name=['Sheet 1', 2, 3], header=9, usecols="A,B,D:H", nrows=19)
print(type(df_complex))  # <class 'dict'>
df_complex#['Sheet 1'].head(10)

### 1.2.7. Pandas读取XML数据 

XML（eXtensible Markup Language）是一种标记语言，广泛应用于数据存储、数据交换和配置文件等领域。特征：1. 每个数据都用Tags框住，文本和HTML格式相似。但没有预设的Tags， 2. 具有特定结构：可以多级内嵌, 3. 基本组成：元素（Element）和属性（Attribute）：可以理解为是要被读取的数据和相应的说明。

XML数据通常的处理方法：
1. 组合法：先用Python内置或第三方库来解析XML文本，找出元素和属性，再将找到的元素和属性交给pd.DataFrame()转换成df
2. 直接使用Pandas的read_xml()

#### 1.2.7.1. XML第一种处理方法举例

In [25]:
from lxml import objectify

"""sample.xml content

<INDICATOR>

<INDICATOR_SEQ>373889</INDICATOR_SEQ>

<PARENT_SEQ></PARENT_SEQ>

<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
<DESCRIPTION>Percent of the time that escalators are operational
systemwide. The availability rate is based on physical observations 244
the morning of regular business days only. This is a new indicator began
reporting in 2009.</DESCRIPTION>

<MONTHLY_TARGET>97.00</MONTHLY_TARGET>
<MONTHLY_ACTUAL></MONTHLY_ACTUAL>

</INDICATOR>
"""

'sample.xml content\n\n<INDICATOR>\n\n<INDICATOR_SEQ>373889</INDICATOR_SEQ>\n\n<PARENT_SEQ></PARENT_SEQ>\n\n<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>\n<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>\n<DESCRIPTION>Percent of the time that escalators are operational\nsystemwide. The availability rate is based on physical observations 244\nthe morning of regular business days only. This is a new indicator began\nreporting in 2009.</DESCRIPTION>\n\n<MONTHLY_TARGET>97.00</MONTHLY_TARGET>\n<MONTHLY_ACTUAL></MONTHLY_ACTUAL>\n\n</INDICATOR>\n'

In [26]:
xml_df = {}
parsed = objectify.parse(open('data/sample.xml','r'))
root = parsed.getroot()
for child in root.getchildren():
        xml_df[child.tag]=str(child)
pd.DataFrame(xml_df,index=[1])

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,MONTHLY_TARGET,MONTHLY_ACTUAL
1,373889,,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,97.0,

#### 1.2.7.1. XML第二种处理方法举例

In [24]:
df = pd.read_xml('data/sample.xml',xpath='//INDICATOR')
df

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,MONTHLY_TARGET,MONTHLY_ACTUAL
0,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,97.0,NaN

## 1.3.数据探索和理解

### 1.3.1. 理解和掌握Pandas数据的灵魂操作手：Index标签  

Index给与用户一个工具和机会来掌控Pandas的数据（主要是DataFrame类型）：“挟标签（天子）以令诸侯”， “牵一标签（发）而动全身”。

用户体验：
- ”不就是数码文字说明吗？有什么难的“ （=“围城”之预入城入坑者）
- “脑壳子疼，一脑子浆糊，怎么用法这么乱呢？”  （=“围城”之预出城逃难者）

心得：


玩转Pandas的Index标签  
1. 知识点和理解框架：
- 对Index标签本身的操作：
  - 你想做什么：
    - 构建
    - 修改
    - 删除
    - 指定/设置标签，  重制标签
  - 你得知道怎么做：
    - df.set_index(), df.reset_index()
- 用标签（Index）来对数据的操作=索引（Indexing）：
  - 你想做什么：
    - 筛选（整串， 或局部=切片）
    - 排序
    - 添加/删除
    - 转换
    - 分组/整合/拼接
  - 你得知道怎么做：
    - df[], df.loc(), df.iloc()


1. 运用：
   - 从简单到复杂地练习
   - 对大家有帮助的一个方法选择的逻辑分析框架：
    问：自己是否知道数据的固定范围？ 答是的，“出门向左”，继续走1。答否的，“出门向右”，问：自己是否知道想要怎样的数据， 但不知道在表格里都是分布/位置？ 答是的，“一路向北”，继续2。答否的：“更上一层楼”，思考是否任务太大，需要分解目标。
     1. 自己知道数据的固定位置或范围
     2. 自己不确定数据位置/范围，需要采用某种筛选条件来选择
     3. 自己不知道如何来框定数据，想法太复杂（“我想要一份红烧排骨来炖干煸排骨汤”），思考你的思考

练习

set_index() 将已存在的列标签(对应内容)设置为 DataFrame 行索引。除了可以添加索引外，也可以替换已经存在的索引。常见场景：把 Series 或者一个 DataFrame 设置成另一个 DataFrame 的索引

reset_index() ： 恢复初始行索引

In [ ]:
df_list = pd.read_csv('data/contact_person.txt', sep=" ",encoding='latin-1',header=0)
#设置department为行索引
print(df_list.set_index('department'))

info = pd.DataFrame([('William', 'C'), 
('Smith', 'Java'), 
('Parker', 'Python'), 
('Phill', np.nan)], 
index=[1, 2, 3, 4], 
columns=('name', 'Language')) 
print(f"Before Reset:\n {info}")
print(f"After Reset:\n {info.reset_index()}")

### 1.3.2. 熟悉数据属性 
→ 熟悉Pandas数据属性的查看方法

步骤：
- 熟悉数据属性：
  - 抽样查看数据。方法：
    - df.head(n):查看首个(n)行数据
    - df.tail(n)：查看最后(n)行数据
    - df.sample(n)： 随机查看（n）行数据
  - 检查数据基本信息/类型和形状. 方法：
    - df.info: 显示所有数据的类型、索引情况、行列数、各字段数据类型、内存占用等。注意：Series不支持
    - df.dtype: 返回每个字段的数据类型及DataFrame整体的类型
    - df.shape:  返回一个set（行数，列数）。注意：不包含索引。Series结构：列数为空
- 数据检测 （Sanity Check）
  - df.describe()： 返回df数据的统计信息（表格形式），每一行对应一个统计指标，如总数、均值、标准差、最小值、四分位数、最大值等。

#### 练习

## 2. 数据预处理 Data Preparation  <a id="2"></a>

好数据的评估指标：准确，完整，一致，可调用，合规

必要流程：
- 数据清洗（Data Cleaning）
  - 缺失值
  - （异常值发现和处理）
- 数据准备：  
- 数据转换
- 数据调整

### 2.1 掌握Pandas索引

#### 2.1.1 Pandas数据的索引操作

基础知识点和必备技能：
 - 了解Pandas索引的种类
 - 索引的构建（包含）
 - 索引的重建（保留/覆盖原索引）

#### 2.1.2 通过操作索引来操作Pandas数据

基础知识点和必备技能：
- 用索引来筛选数据

## 3. 数据分析和探索，建模  Data Analysis & Data  Mining，Modelling <a id="3"></a>

方法：
1. 统计学分析
   1. 发现和处理异常值
2. 行业领域分析
3. 分析结果可视化

### 基于数据的建模

我们可以思考如何从现有的数据中提取更具有价值的信息，通常的方法就是建立一些自己的观点=模型，再验证。

在第一个Python学习项目中，我们可以思考如下：
- 建立用户年龄和购买关系的模型：
  - 假设：销售额和用户年龄相关 → 建立一个用户年龄和销售额的关系模型 →通过数学解析或图解法求得该关系 → 验证自己的假设是否属实（证实或证伪）
- 建立一个用户年龄和区域的关系： → 自己尝试
  - 假设：不同区域的人群拥有某个显性的购买趋向 → 建立一个用户年龄和地域的关系模型 → 通过数学解析或图解法求得对应关系 → 验证假设

### 数据可视化

了解和学习使用画图专业户matplotlib

## 4. 模型评估 Model Evaluation <a id="4"></a>

## 5. 业务理解/知识深化和提升  <a id="5"></a> 

总结：
项目目标: 通过实际案例学习和熟悉Pandas的读取最常见数据类型的方法，基础操作。

练习步骤：


学习体会和反馈？

如何玩转Pandas的Index？
心得体会： 
- 一般的常识：功能越广泛， 操作设计就会越复杂。 
- Index的设计就很贴切
- 很多人在使用过程中，往往会对变化多端的用法和各种各样的规矩产生疑惑（比如衍生型的索引使用）
- 学习复杂的方法，切忌死记硬背，效果最差。最有效的方法是搞清楚它的设计逻辑和相关的主要注意点。 如同展开逆向工程来理解造物主的想法。
- 对于复杂的筛选方法的困惑，原因或主要在于理不清筛选条件的适用范围和返回值