# 数据科学/数据处理的流程

## Project name: ds_proj_pd01

文件来源： 此文件出自Python For Beginner学习社群。

作者： 闫小峰

Last Update: 2025-09-17

## 数据处理通用框架/流程模板

[0. 业务理解 Understanding](#0) 

[1. 数据获取和理解 ](#1)
- 数据分析环境设置 Set Up Environment
- 数据获取/采样
- 数据探索  
  - 熟悉数据属性
  - 数据体检： Sanity Checking 

[2. 预处理 Data Preparation](#2)  
- 数据清理  Data Cleaning 
- 数据准备，转换和调整


[3. 数据分析和挖掘 Data Analysis / Data  Mining](#3)
- 传统（经典）数据分析： 
  - 统计学方法 
  - 建模： 业务分析模型
- 机器学习 Machine Learning: 
  - 模型构建: 训练-测试-调试， 
  - 模型预测
- AI增强/辅助型数据分析和开发
  - LLM

[4. 模型评估  Model Evaluation ](#4)


[5. 业务理解/知识深化和提升](#5)
- 数据处理流程自动化 Pipelines
- X by Data Based/Data Driven
   -  Decision Making
   -  Story Line
   -  逻辑论证
   -  发现规律 etc

# 0.业务理解Understanding

- 目标和需求分析：
  - 目的：玩转Pandas！
    - 岗位基本操作训练：学习+练习Pandas基础结构
    - 熟悉使用Pandas读取和输出各种类型的数据（Text，Markdown，HTML，JSON，CSV，XLSX，URL）
    - 敲黑板：重点玩转Pandas的索引操作
    - 学习数据清理的技巧，了解数据清理的灵活度
- 操作执行战术分析：
  - 阶段性要求：
    - 能够实现数据读取自由
    - 进阶：Excel表格的选择读取（职场中的痛点）
    - 没有涵盖：网页爬虫爬取数据
    - 能够灵活处理缺失值和异常值

  - 数据分析需要的方法
  
- 业务理解
  - 暂无

# 1. 数据获取和理解 Get Data & Data Understanding <a id="1"></a>

### 1.1. 数据处理环境设置 Set Up Environment <a id="1.1"></a>

In [2]:
# import modules for data science 
import numpy as np
import pandas as pd

#import module for plotting
import matplotlib.pyplot as plt 
#import rcParams um chinesische Texte richtig in Matplotlib anzuzeigen
from matplotlib import rcParams
# Setze die chin. Schriftart für den Titel, die in Matpolotlib angezeigt werden kann
rcParams['font.family'] = 'SimHei'  # oder 'Microsoft YaHei'

import warnings
warnings.filterwarnings('ignore') #to suppress warning messages


#import pybds_lib as pds

%load_ext autoreload
%autoreload 2
%matplotlib inline

## 1.2.数据获取

### 1.2.1. Pandas读取数据方法总结


Pandas官网不同数据类型的读取存储方法[1]

Reference：  
[1]: https://pandas.pydata.org/docs/reference/io.html

#### 1.2.1. Pandas读取Text数据方法


读取以 txt格式保存的表格数据可以使用：  
pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='\t',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定txt中的分割符. tab: '\t'
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [3]:
try:
    # Try 'latin-1' (ISO-8859-1), a common fallback for text files
    df_list = pd.read_csv('../Chapter03/b03_data/contact_person.txt', sep=" ",encoding='latin-1',header=0)
    print("Successfully read with latin-1 encoding.")
except UnicodeDecodeError:
    print("Could not decode with common encodings. Please inspect the file.")

df_list.head()

Successfully read with latin-1 encoding.

     name surname         dob   department
0  George   Brown  12/02/1993  Engineering
1  Andrew   Black  15/04/1975           HR
2   Maria   Green  12/02/1989  Engineering
3   Helen     Fox  21/10/2000    Marketing
4     Joe     Xiu  10/11/1998  Engineering

#### 1.2.2. Pandas读取Markdown数据方法

读取md格式中的表格的概率较小，更常用的场景是将处理好的数据写入Markdown文件中的表格。

pd.to_markdown()方法

#### 1.2.3. Pandas读取HTML数据方法

pd.read_html()方法
- 只能读取网页中的表格(即<table>标签内的数据)    

pd.read_html(io, *[, match, flavor, header, ...])  - options

参数说明：  
- io: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接.注意：网址不接受https
- match: 字符串，正则表达式
- flavor：解释器。默认“lxml”
- header：整数，指定列名所在的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。

In [13]:
import urllib.request

url = 'http://en.wikipedia.org/wiki/2008_Summer_Olympics'
headers = {'User-Agent': 'Mozilla/5.0'}
req = urllib.request.Request(url, headers=headers)   #return a request object

# turn request object into file like object or string, in oder to read it with pd.read_html
with urllib.request.urlopen(req) as response:
    html = response.read()

medal_table = pd.read_html(html, match='2008 Summer Olympics medal table')

print(medal_table)

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [15]:
#url = 'http://en.wikipedia.org/wiki/2020_Summer_Olympics'
url = r"../Chapter03/b03_data/2008%20Summer%20Olympics%20-%20Wikipedia.htm"
# Read all tables from the page
tables = pd.read_html(url)

# Find the medal table by matching its title
for table in tables:
    if 'Nation' in table.columns or 'NOC' in table.columns:
        medal_table = table
        break

# Display the medal table
medal_table.head()

ImportError: Missing optional dependency 'html5lib'.  Use pip or conda to install html5lib.

#### 1.2.4. Pandas读取JSON数据方法

待补充完善！

#### 1.2.5. Pandas读取CSV数据方法

pd.read_csv() - Options

>**pandas.`read_csv`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file_path_or_buffer,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sep='',<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encoding=None) <br>

参数说明：  
- file_path_or_buf: 字符串（用单/双引号），被导入的带路径的文件名，也可以是URL链接
- sep: 字符串，指定CSV中的分割符
- header：整数，指定源文件作为列名的行数。默认值：0. 无列名：None
- encoding：字符串，指定文件的编码格式。默认值：None

In [ ]:
#df=pd.read_csv('data.csv')          # 如果文件与代码文件在同一目录下
df=pd.read_csv('../Chapter03/b03_data/b03_births.csv',sep=',')  # 指定目录
# 使用URL

df.head()

   year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

#### 1.2.6. Pandas读取Excel Table数据方法

pd.read_excel() - Options

>**pandas.`read_excel`**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;io,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sheet_name=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;usecols=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nrows=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;true_values=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skiprows=None，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skipfooter=0，<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;converters=None,<br> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dtype=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)

参数说明：
- io： 直接使用pd.read_excel(r"文件路径")，默认读取第一个sheet的全部数据。 支持str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
- sheet_name：可选（str, int, list, None, default 0）
  - str: 字符串用于引用的sheet的名称(如果有特定名称)
  - int: 整数用于引用的sheet的隐性索引（从0开始）
  - list：整数和字符串组成的列表，读取后的数据类型是OrderedDict,将列表指定的sheet的数据合并到了一个list中
  - None：表示引用所有sheet （相当于=list（all）的结果）
  - 0： 默认第一个sheet
- header: 表示用第几行作为表头，可选（int, list of int, default 0）
  - 0： 默认，即第一行为表头 
  - int: 跳选第int+1行为表头，前面行数据就被忽略了。行数从0开始
  - [int]：选择列表int指定行的数据作为表头。可用于读取合并行数据做表头
  - None: 不用源表头
- usecols:可选(int, str, list-like, or callable default None)
  - None：默认值，解析所有列。
  - str： 表示Excel列字母。列范围的逗号分隔列表（例如“ A：E”或“ A，C，E：F”）。`范围全闭`。
  - int: 解析到第几列。`对应隐性列索引，从0开始，但是范围全闭（容易让人抓狂的地方）`。 如usecols=3: 选0，1，2，3共4列数据
  - int列表: 解析int对应的那几列。
- index_col：指定列为索引列，可选（int, list of int, default None）
  - 默认为None，即隐性的行作DataFrame的行标签。
  - int: 指定第几列为索引列. 从0开始。
  - list of int：选择列表中的整数列为索引列（多重列索引）
- nrows：（int, default None），指定需要读取前多少行，通常用于较大的数据文件中。注意：从header行下一行开始算！
  - 默认为None
  - int：nrows=3 读取前三行
- skiprows：跳过指定的行，可选（int，list like）
  - int: 跳过前int行=从int+1行开始读取
  - [int]：skiprows=[1,3,5] 跳过第1,3,5行
- dtype: 指定读入的列的数据类型。可选（Type name or dict of column -> type, default None）
  - 默认为None，也就是不改变数据类型
  - 指定列的类型名称或字典。
  - 场景：作用强大，强制限制数据类型，避免后续处理出现意外。如原始字符串数字被当成数值进行运算。可结合df.info先查看各列数据类型是否合乎要求

In [ ]:
# 最简单方法： Excel文件无脑读取
df = pd.read_excel("data/simple_tables.xlsx")
#df.head()
df.tail()

,Some Data,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Some Explanation
19,Bart Simpson,24,17.88,5.5,0.12,0.4,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Iron Man,12,1.44,7.1,0.55,0.5,-0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Thomas H.,20,2,2,0.11,0.6,0.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,144.3,82.685,28.08,0.451,0.55,0.099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 通常还需要细选某个区域的数据，需要指定行列索引
#
df = pd.read_excel("data/simple_tables.xlsx", header=1, usecols="A:M", nrows=7)
df.head(10)

,Main Column,January,February,March,April,May,June,July,August,September,October,November,December
0,Value 1,123.000000,321.000000,312.000000,213.000000,312.000000,222.000000,111.000000,124.000000,0,0,0,0
1,Value 2,67.000000,34.000000,56.000000,76.000000,123.000000,545.000000,444.000000,442.000000,0,0,0,0
2,Value 3,78.000000,23.000000,77.000000,77.000000,222.000000,434.000000,544.000000,234.000000,0,0,0,0
3,Value 4,89.000000,12.000000,56.000000,55.000000,33.000000,333.000000,654.000000,423.000000,0,0,0,0
4,Value 5,0.491632,0.478972,0.579097,0.638244,0.511928,0.675326,0.606272,0.762846,0,0,0,0
5,Value 6,0.889900,0.920011,0.732506,0.671966,0.616595,0.667848,0.868355,0.276603,0,0,0,0
6,Value 7,0.437504,0.440660,0.424193,0.428878,0.315652,0.451015,0.526459,0.211006,0,0,0,0

In [ ]:
# 复杂的Excel文件（比如多个sheet），可以先获取一些基本信息
# 读取sheet名称
df = pd.read_excel("data/complex_tables.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Dramatic Headline!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Type 1,NaN,Confident,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,JA,Headline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 面对复杂的Excel文件（比如多个sheet），需要指定更多参数
#
df = pd.read_excel("data/complex_tables.xlsx", sheet_name='Sheet 1', header=9, usecols="A:H", nrows=7)
df.head(20)

,#,Person,Description,Column 4,Column 5,Column 6,Column 7,Column 8
0,123,Person 1,Description 1,15.00,650,432.12,6481.8000,9750.00
1,124,Person 2,Description 2,14.50,650,432.12,6265.7400,9425.00
2,125,Person 3,Description 3,0.25,555,432.12,108.0300,138.75
3,126,Person 4,Description 4,2.12,555,432.12,916.0944,1176.60
4,127,Person 5,Description 5,5.64,650,432.12,2437.1568,3666.00
5,128,Person 6,Description 6,12.10,400,432.12,5228.6520,4840.00
6,129,Person 7,Description 7,3.56,300,432.12,1538.3472,1068.00

In [ ]:
df_complex = pd.read_excel("data/complex_tables.xlsx", sheet_name=['Sheet 1', 2, 3], header=9, usecols="A,B,D:H", nrows=19)
print(type(df_complex))  # <class 'dict'>
df_complex['Sheet 1'].head(10)
print(df_complex[3].head(19))

<class 'dict'>
        #     Person  Column 4  Column 5  Column 6    Column 7  Column 8
0   123.0   Person 1    15.000     650.0    432.12   6481.8000   9750.00
1   124.0   Person 2    14.500     650.0    432.12   6265.7400   9425.00
2   125.0   Person 3     0.250     555.0    432.12    108.0300    138.75
3   126.0   Person 4     2.120     555.0    432.12    916.0944   1176.60
4   127.0   Person 5     5.640     650.0    432.12   2437.1568   3666.00
5   128.0   Person 6    12.100     400.0    432.12   5228.6520   4840.00
6   129.0   Person 7     3.560     300.0    432.12   1538.3472   1068.00
7   130.0   Person 8    11.450     450.0    432.12   4947.7740   5152.50
8   131.0   Person 9    22.320     550.0    432.12   9644.9184  12276.00
9   132.0  Person 10    20.180     425.0    432.12   8720.1816   8576.50
10  133.0  Person 11    32.000     375.0    432.12  13827.8400  12000.00
11  134.0  Person 12     5.570     650.0    432.12   2406.9084   3620.50
12  135.0  Person 13     8.875     750.0    444.00   3940.5000   6656.25
13  136.0  Person 14     3.250     555.0    432.12   1404.3900   1803.75
14  137.0  Person 15    12.230     475.0    432.12   5284.8276   5809.25
15  138.0  Person 16     0.330     650.0    575.00    189.7500    214.50
16  139.0  Person 17     2.750     123.0    432.12   1188.3300    338.25
17    NaN        NaN       NaN       NaN       NaN         NaN       NaN
18    NaN        NaN       NaN       NaN       NaN         NaN      0.00

In [ ]:
# optional: get rid of rows with NA to get clear data for each sheet
df_sheet1 = df_complex['Sheet 1'].dropna()
df_sheet2 = df_complex[2].dropna()
df_sheet3 = df_complex[3].dropna()
df_sheet1.head(7)

       #    Person  Column 4  Column 5  Column 6   Column 7  Column 8
0  123.0  Person 1     15.00     650.0    432.12  6481.8000   9750.00
1  124.0  Person 2     14.50     650.0    432.12  6265.7400   9425.00
2  125.0  Person 3      0.25     555.0    432.12   108.0300    138.75
3  126.0  Person 4      2.12     555.0    432.12   916.0944   1176.60
4  127.0  Person 5      5.64     650.0    432.12  2437.1568   3666.00
5  128.0  Person 6     12.10     400.0    432.12  5228.6520   4840.00
6  129.0  Person 7      3.56     300.0    432.12  1538.3472   1068.00

In [ ]:
# read excel data from sheet "Orders" 
# Specify Sheet Name
df = pd.read_excel("data/complex_tables.xlsx", sheet_name='Orders')

"""
# Specify Row (0-indexed) to use for the column labels
df = pd.read_excel("data/complex_tables.xlsx",sheet_name='Orders', header=5)
                   """
df.tail(7)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
3311,NaN,CA-2017-163629,NaN,NaN,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.99,1,0%,28.7964,NaN,NaN,NaN,NaN
3312,NaN,CA-2017-163629,NaN,NaN,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1,5,0%,55.647,NaN,NaN,NaN,NaN
3313,NaN,CA-2017-121258,Yes,NaN,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0%,15.6332,NaN,NaN,NaN,NaN
3314,NaN,CA-2017-121258,Yes,NaN,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,20%,19.3932,NaN,NaN,NaN,NaN
3315,NaN,CA-2017-121258,Yes,NaN,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0%,13.32,NaN,NaN,NaN,NaN
3316,NaN,CA-2017-119914,NaN,NaN,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0%,72.948,NaN,NaN,NaN,NaN
3317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,733215.2552,12476,NaN,93439.2696,NaN,NaN,NaN,NaN

In [ ]:
# Select different column range
df = pd.read_excel("data/complex_tables.xlsx",
                   sheet_name='Orders',
                   header=5,
                   usecols='B,C,E:N')
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,20%,5.4432
1,US-2017-156909,NaN,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,30%,-1.0196
2,CA-2017-107727,NaN,7090.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,20%,9.9468
3,CA-2017-120999,Yes,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,20%,16.5564
4,CA-2017-139619,NaN,1852.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,20%,9.5616

In [ ]:
# Specify values to consider as True.
df = pd.read_excel("data/complex_tables.xlsx",
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C,E:N',
                   true_values=['Yes']
                   )
df.head()

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,20%,5.4432
1,US-2017-156909,NaN,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,30%,-1.0196
2,CA-2017-107727,NaN,7090.0,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,20%,9.9468
3,CA-2017-120999,True,60540.0,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,20%,16.5564
4,CA-2017-139619,NaN,1852.0,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,20%,9.5616

In [ ]:
# Rows at the end to skip 
df = pd.read_excel("data/complex_tables.xlsx",
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C,E:N',
                   true_values=['Yes'],
                   skipfooter = 2
                   )
df.tail(10)

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
3301,CA-2017-141446,NaN,41042,South,TEC-AC-10002305,Technology,Accessories,KeyTronic E03601U1 - Keyboard - Beige,18.000,1,0%,3.2400
3302,CA-2017-153871,NaN,7060,East,OFF-BI-10004209,Office Supplies,Binders,"Fellowes Twister Kit, Gray/Clear, 3/pkg",40.200,5,0%,18.0900
3303,CA-2017-153871,NaN,7060,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.980,2,0%,331.1910
3304,CA-2017-153871,NaN,7060,East,OFF-AP-10003622,Office Supplies,Appliances,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",22.750,7,0%,6.5975
3305,CA-2017-163566,NaN,45014,East,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.520,5,20%,5.3690
3306,CA-2017-163629,NaN,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0%,28.7964
3307,CA-2017-163629,NaN,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0%,55.6470
3308,CA-2017-121258,True,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0%,15.6332
3309,CA-2017-121258,True,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,20%,19.3932
3310,CA-2017-121258,True,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0%,13.3200

In [ ]:
# learn first time to convert percentage into float numbers
# 打印 DataFrame 的信息摘要来检查含百分比列的数据类型
df.info()

# Check type
print(f"Discount的数据类型是:  {type(df['Discount'].iloc[0])}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3311 entries, 0 to 3310
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      3311 non-null   object
 1   Returned      288 non-null    object
 2   Postal Code   3311 non-null   int64
 3   Unnamed: 5    3311 non-null   object
 4   Product ID    3311 non-null   object
 5   Category      3311 non-null   object
 6   Unnamed: 8    3311 non-null   object
 7   Product Name  3311 non-null   object
 8   Sales         3311 non-null   float64
 9   Quantity      3311 non-null   int64
 10  Discount      3311 non-null   object
 11  Profit        3311 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 310.5+ KB
Discount的数据类型是:  <class 'str'>

In [ ]:

# Attetion: String cannot perform math operations!
test_op = '20%' * 2
print(f"no math operation for string %: {test_op}")

# Create Function to covert % to float
def convert_string_to_float(row):
    '''Convert string (%) to float'''
    pct_value = row.replace('%','')
    pct_value = float(pct_value) / 100
    return pct_value

# Converters: Dict of functions for converting values in certain columns
df = pd.read_excel("data/complex_tables.xlsx",
                   sheet_name='Orders',
                   header=5,
                   usecols='B:C,E:N',
                   true_values=['Yes'],
                   skipfooter = 2,
                   converters={'Discount': convert_string_to_float}
                   )
df.head()

no math operation for string %: 20%20%

,Order ID,Returned,Postal Code,Unnamed: 5,Product ID,Category,Unnamed: 8,Product Name,Sales,Quantity,Discount,Profit
0,CA-2017-114412,NaN,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
1,US-2017-156909,NaN,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
2,CA-2017-107727,NaN,7090,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
3,CA-2017-120999,True,60540,Central,TEC-PH-10004093,Technology,Phones,Panasonic Kx-TS550,147.168,4,0.2,16.5564
4,CA-2017-139619,NaN,1852,South,OFF-ST-10003282,Office Supplies,Storage,"Advantus 10-Drawer Portable Organizer, Chrome ...",95.616,2,0.2,9.5616

### 1.2.7. Pandas读取XML数据 

XML（eXtensible Markup Language）是一种标记语言，广泛应用于数据存储、数据交换和配置文件等领域。特征：1. 每个数据都用Tags框住，文本和HTML格式相似。但没有预设的Tags， 2. 具有特定结构：可以多级内嵌, 3. 基本组成：元素（Element）和属性（Attribute）：可以理解为是要被读取的数据和相应的说明。

XML数据通常的处理方法：
1. 组合法：先用Python内置或第三方库来解析XML文本，找出元素和属性，再将找到的元素和属性交给pd.DataFrame()转换成df
2. 直接使用Pandas的read_xml()

#### 1.2.7.1. XML第一种处理方法举例

In [ ]:
from lxml import objectify

"""sample.xml content

<INDICATOR>

<INDICATOR_SEQ>373889</INDICATOR_SEQ>

<PARENT_SEQ></PARENT_SEQ>

<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
<DESCRIPTION>Percent of the time that escalators are operational
systemwide. The availability rate is based on physical observations 244
the morning of regular business days only. This is a new indicator began
reporting in 2009.</DESCRIPTION>

<MONTHLY_TARGET>97.00</MONTHLY_TARGET>
<MONTHLY_ACTUAL></MONTHLY_ACTUAL>

</INDICATOR>
"""

'sample.xml content\n\n<INDICATOR>\n\n<INDICATOR_SEQ>373889</INDICATOR_SEQ>\n\n<PARENT_SEQ></PARENT_SEQ>\n\n<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>\n<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>\n<DESCRIPTION>Percent of the time that escalators are operational\nsystemwide. The availability rate is based on physical observations 244\nthe morning of regular business days only. This is a new indicator began\nreporting in 2009.</DESCRIPTION>\n\n<MONTHLY_TARGET>97.00</MONTHLY_TARGET>\n<MONTHLY_ACTUAL></MONTHLY_ACTUAL>\n\n</INDICATOR>\n'

In [ ]:
xml_df = {}
parsed = objectify.parse(open('data/sample.xml','r'))
root = parsed.getroot()
for child in root.getchildren():
        xml_df[child.tag]=str(child)
pd.DataFrame(xml_df,index=[1])

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,MONTHLY_TARGET,MONTHLY_ACTUAL
1,373889,,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,97.0,

#### 1.2.7.1. XML第二种处理方法举例

In [12]:
df = pd.read_xml('data/sample.xml',xpath='//INDICATOR')
df

XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

## 1.3.数据探索和理解

### 1.3.1. 理解和掌握Pandas数据的灵魂操作手：Index标签  

Index给与用户一个工具和机会来掌控Pandas的数据（主要是DataFrame类型）：“挟标签（天子）以令诸侯”， “牵一标签（发）而动全身”。

用户体验：
- ”不就是数码文字说明吗？有什么难的“ （=“围城”之预入城入坑者）
- “脑壳子疼，一脑子浆糊，怎么用法这么乱呢？”  （=“围城”之预出城逃难者）

心得：
- 学会用标签索引做支点来撬动数据宇宙
- 心中有两条路径烂熟于心，且运用自如（“明线”，“暗线”）

玩转Pandas的Index标签  
1. 知识点和理解框架：
- 对Index标签本身的操作：
  - 你想做什么：
    - 构建
    - 修改
    - 删除
    - 指定/设置标签，  重制标签
  - 你得知道怎么做：
    - df.set_index(), df.reset_index()
- 用标签（Index）来对数据的操作=索引（Indexing）：
  - 你想做什么：
    - 筛选（整串， 或局部=切片）
    - 排序
    - 添加/删除
    - 转换
    - 分组/整合/拼接
  - 你得知道怎么做：
    - df[], df.loc(), df.iloc()


1. 运用：
   - 从简单到复杂地练习
   - 对大家有帮助的一个方法: 
     - 选择df[], df.loc(), df.iloc()的逻辑分析框架：
    问：自己是否知道数据的固定范围？ 答是的，“出门向左”，继续走1。答否的，“出门向右”，问：自己是否知道想要怎样的数据， 但不知道在表格里都是分布/位置？ 答是的，“一路向北”，继续2。答否的：“更上一层楼”，思考是否任务太大，需要分解目标。
     1. 自己知道数据的固定位置或范围
     2. 自己不确定数据位置/范围，需要采用某种筛选条件来选择
     3. 自己不知道如何来框定数据，想法太复杂（“我想要一份红烧排骨来炖干煸排骨汤”），思考你的思考

#### 1.3.2. Pandas索引操作完整框架练习

##### 1.3.2.1. 索引生命周期管理（Index本身的操作）

| 操作类型 | 目的 | 核心方法 | 代码示例 |
|----------|------|----------|----------|
| 创建构建 | 从数据创建索引   | `pd.index()`, `set_index()` | `df.set_index('日期')` |
| 修改调整 | 重命名/替换索引  | `rename()`, `set_index()` | `df.rename(index={'old':'new'})` |
| 重置恢复 | 索引变列，恢复默认 | `reset_index()` | `df.reset_index(drop=True)` |
| 删除清理 | 移除索引        | `reset_index(drop=True)` | `df.reset_index(drop=True)` |
| 类型转换 | 改变索引数据类型 | `astype()`, `pd.to_datetime()` | `df.index.astype('category')` |

注释：
- set_index() 将已存在的列标签(对应内容)设置为 DataFrame 行索引。除了可以添加索引外，也可以替换已经存在的索引。常见场景：把 Series 或者一个 DataFrame 设置成另一个 DataFrame 的索引

- reset_index() ： 恢复初始行索引

In [7]:
df_list = pd.read_csv('../Chapter03/b03_data/contact_person.txt', sep=" ",encoding='latin-1',header=0)
#设置department为行索引
print(df_list.set_index('department'))

info = pd.DataFrame([('William', 'C'), 
('Smith', 'Java'), 
('Parker', 'Python'), 
('Phill', np.nan)], 
index=[1, 2, 3, 4], 
columns=('name', 'Language')) 
print(f"Before Reset:\n {info}")
print(f"After Reset:\n {info.reset_index()}")

               name    surname         dob
department
Engineering  George      Brown  12/02/1993
HR           Andrew      Black  15/04/1975
Engineering   Maria      Green  12/02/1989
Marketing     Helen        Fox  21/10/2000
Engineering     Joe        Xiu  10/11/1998
Engineering     Ben    Simsons  01/12/1987
Marketing      Jess  Middleton  12/12/1997
Before Reset:
       name Language
1  William        C
2    Smith     Java
3   Parker   Python
4    Phill      NaN
After Reset:
    index     name Language
0      1  William        C
1      2    Smith     Java
2      3   Parker   Python
3      4    Phill      NaN

In [8]:
# 你可以自己定义列标签的排列顺序，用列表方式来规定排
pd.DataFrame(df_list, columns=['dob', 'surname', 'name'])

          dob    surname    name
0  12/02/1993      Brown  George
1  15/04/1975      Black  Andrew
2  12/02/1989      Green   Maria
3  21/10/2000        Fox   Helen
4  10/11/1998        Xiu     Joe
5  01/12/1987    Simsons     Ben
6  12/12/1997  Middleton    Jess

In [73]:

pd.DataFrame(df_list, columns=['surname','dob', 'name'])

     surname         dob    name
0      Brown  12/02/1993  George
1      Black  15/04/1975  Andrew
2      Green  12/02/1989   Maria
3        Fox  21/10/2000   Helen
4        Xiu  10/11/1998     Joe
5    Simsons  01/12/1987     Ben
6  Middleton  12/12/1997    Jess

In [9]:
# 如果你添加了一个新列标签， 在赋值之前，新列会显示缺失值
df_list2 = pd.DataFrame(df_list, columns=['name', 'surname', 'dob', 'department','wealth'])

print(f"DataFrame df_list2 after re-ordering of columns:\n{df_list2}")

# 如果你想替换默认行标签，采用下面的构建方法会出现意外惊喜 
df_list3 = pd.DataFrame(df_list, index=['one', 'two', 'three', 'four','five','six','seven'])

print(f"DataFrame df_list2 after setting index in creation:\n{df_list3}")
#添加了一个新列标签， 在赋值之前，新列会显示缺失值

#重新定义行标签Index的正确方法：
df_list2.index = ['one', 'two', 'three', 'four','five','six','seven']
print(f"DataFrame df_list2 after setting index correctly:\n{df_list2}")

DataFrame df_list2 after re-ordering of columns:
     name    surname         dob   department  wealth
0  George      Brown  12/02/1993  Engineering     NaN
1  Andrew      Black  15/04/1975           HR     NaN
2   Maria      Green  12/02/1989  Engineering     NaN
3   Helen        Fox  21/10/2000    Marketing     NaN
4     Joe        Xiu  10/11/1998  Engineering     NaN
5     Ben    Simsons  01/12/1987  Engineering     NaN
6    Jess  Middleton  12/12/1997    Marketing     NaN
DataFrame df_list2 after setting index in creation:
      name surname  dob department
one    NaN     NaN  NaN        NaN
two    NaN     NaN  NaN        NaN
three  NaN     NaN  NaN        NaN
four   NaN     NaN  NaN        NaN
five   NaN     NaN  NaN        NaN
six    NaN     NaN  NaN        NaN
seven  NaN     NaN  NaN        NaN
DataFrame df_list2 after setting index correctly:
         name    surname         dob   department  wealth
one    George      Brown  12/02/1993  Engineering     NaN
two    Andrew      Black  15/04/1975           HR     NaN
three   Maria      Green  12/02/1989  Engineering     NaN
four    Helen        Fox  21/10/2000    Marketing     NaN
five      Joe        Xiu  10/11/1998  Engineering     NaN
six       Ben    Simsons  01/12/1987  Engineering     NaN
seven    Jess  Middleton  12/12/1997    Marketing     NaN

In [16]:
#重新改回默认行标签Index：
df_list2.reset_index(drop=True, inplace=True)
print(f"DataFrame df_list2 after re-setting default index:\n{df_list2}")

#你可以把整列 "wealth"从df_list2中删除，使用drop方法：
df_list2_dropped = df_list2.drop('wealth', axis=1)  # 轴向操作：axis=1规定列, axis=0指定行
#也可以使用以下方法：
# df_list2_dropped = df_list2.drop(columns=['wealth']) 

print(f"DataFrame df_list2 after dropping 'wealth' column:\n{df_list2_dropped}")

df = df_list.copy()

DataFrame df_list2 after re-setting default index:
     name    surname         dob   department  wealth
0  George      Brown  12/02/1993  Engineering     NaN
1  Andrew      Black  15/04/1975           HR     NaN
2   Maria      Green  12/02/1989  Engineering     NaN
3   Helen        Fox  21/10/2000    Marketing     NaN
4     Joe        Xiu  10/11/1998  Engineering     NaN
5     Ben    Simsons  01/12/1987  Engineering     NaN
6    Jess  Middleton  12/12/1997    Marketing     NaN
DataFrame df_list2 after dropping 'wealth' column:
     name    surname         dob   department
0  George      Brown  12/02/1993  Engineering
1  Andrew      Black  15/04/1975           HR
2   Maria      Green  12/02/1989  Engineering
3   Helen        Fox  21/10/2000    Marketing
4     Joe        Xiu  10/11/1998  Engineering
5     Ben    Simsons  01/12/1987  Engineering
6    Jess  Middleton  12/12/1997    Marketing

索引属性检查

In [17]:
print("索引对象:", df.index)
print("索引值:", df.index.values)
print("索引类型:", type(df.index))
print("索引名称:", df.index.name)
print("索引长度:", len(df.index))
print("是否唯一:", df.index.is_unique)

索引对象: RangeIndex(start=0, stop=7, step=1)
索引值: [0 1 2 3 4 5 6]
索引类型: <class 'pandas.core.indexes.range.RangeIndex'>
索引名称: None
索引长度: 7
是否唯一: True

##### 1.3.2.2. 基于索引的数据访问（用Index操作数据）

1.  选择/筛选

| 方法 | 用途 | 特点 | 代码示例 |
|----------|------|----------|----------|
| []  |	基础列选择	| 只能选列	    |     `df[''pop'']`    |
| .loc[]   | 	标签定位 |	按索引标签选择   |	`df.loc['Texas']`  |
| .iloc[]	| 位置定位   |	按整数位置选择	 |  `df.iloc[0]`   |
| .at[]   |	快速标量访问  |	单个标签取值  |	`df.at['Texas', 'pop']`  |
| .iat[]  |	快速位置访问  | 单个位置取值  |	`df.iat[0, 1]`  |

#### 将 DataFrame 看作字典 ，从字典中创建 Dataframe

In [19]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
display(data.dtypes)
data

area    int64
pop     int64
dtype: object

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [20]:
###1.3.2.3 切片操作
#### 通过列名进行字典形式（dictionary-style）的取值获取数据



display(type(data['area']))

data['area']

pandas.core.series.Series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [21]:
# 🐍 用属性形式（attribute-style）选择纯字符串列名的数据

data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [22]:
# 通过索引标签选择整行行数据
data.loc['Texas']

area      695662
pop     26448193
Name: Texas, dtype: int64

In [23]:
# 🐍 利用列对象，在数据表中增加一列

data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [24]:
# 选择 data 中的 area 和 density 两列
data[['area', 'density']]

              area     density
California  423967   90.413926
Texas       695662   38.018740
New York    141297  139.076746
Florida     170312  114.806121
Illinois    149995   85.883763

In [ ]:
# # 通过索引位置选择整行行数据
display(data.iloc[0])

display(data.iloc[-1])

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

area       1.499950e+05
pop        1.288214e+07
density    8.588376e+01
Name: Illinois, dtype: float64

In [25]:
# 选择数据表中的前两行
display(data.iloc[0:2])
data['Florida':'Illinois']

              area       pop    density
California  423967  38332521  90.413926
Texas       695662  26448193  38.018740

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [ ]:
data['area'].iloc[0:2]

California    423967
Texas         695662
Name: area, dtype: int64

In [ ]:
# 选择数据表中的 area 和 density 两列的第2行到第3行（索引1和2）

data[['area', 'density']].iloc[0:2]

              area    density
California  423967  90.413926
Texas       695662  38.018740

## 选取数据表中单个单元数据的方法

In [30]:
# 通过标签选取数据表中的单个数据 Texas 的面积值  行列标签选取
a= data['area'].loc['Texas']
display(a)

b= data.iloc[1,0]  # 通过行列索引位置选取单个数据 先行位置，后列位置
display(b)

c= data.at['Texas', 'area']  # 通过行列标签选取单个数据 
display(c)

d= data.iat[1,0]  # 通过行列索引位置选取单个数据
display(d)

695662

695662

695662

695662

### 通过布尔掩码选择数据 带条件的筛选

In [37]:
 # 通过布尔掩码选择数据
display(data[data.density > 100])


##在 loc 索引器中结合使用掩码与的索引方法  
data.loc[data.density > 100, ['pop', 'density']]

            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [38]:
# 在 iloc 索引器中结合使用掩码与的索引方法  
data.iloc[data.density > 100, [1, 2]]  # iloc 只能使用索引位置

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [50]:
# Option 1: Use iloc with integer positions
mask = data.density > 100
data.iloc[mask.values, [1, 2]]

# Option 2: Use loc instead (more readable)
data.loc[data.density > 100, data.columns[[1, 2]]]

# Option 3: Chain the operations
data[data.density > 100].iloc[:, [1, 2]]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

#### 1.3.2.3. 索引高级操作

### 重设索引

In [65]:

# 将现有的索引替换为从0开始的新的索引，
data_reset = data.reset_index()
display(data_reset)
# 将index列重命名为state
data_reset = data.reset_index().rename(columns={'index':'state'})
display(data_reset)
df = data_reset

        index    area       pop     density
0  California  423967  38332521   90.413926
1       Texas  695662  26448193   38.018740
2    New York  141297  19651127  139.076746
3     Florida  170312  19552860  114.806121
4    Illinois  149995  12882135   85.883763

        state    area       pop     density
0  California  423967  38332521   90.413926
1       Texas  695662  26448193   38.018740
2    New York  141297  19651127  139.076746
3     Florida  170312  19552860  114.806121
4    Illinois  149995  12882135   85.883763

In [66]:
# 添加州名缩写列
state_abbr = {
    'California': 'CA',
    'Texas': 'TX',
    'New York': 'NY',
    'Florida': 'FL',
    'Illinois': 'IL'
}
df['abbr'] = df['state'].map(state_abbr)
display(df.head())

df.set_index('abbr', inplace=True)
display(df.head())

        state    area       pop     density abbr
0  California  423967  38332521   90.413926   CA
1       Texas  695662  26448193   38.018740   TX
2    New York  141297  19651127  139.076746   NY
3     Florida  170312  19552860  114.806121   FL
4    Illinois  149995  12882135   85.883763   IL

           state    area       pop     density
abbr
CA    California  423967  38332521   90.413926
TX         Texas  695662  26448193   38.018740
NY      New York  141297  19651127  139.076746
FL       Florida  170312  19552860  114.806121
IL      Illinois  149995  12882135   85.883763

### 1.3.2. 熟悉数据属性 
→ 熟悉Pandas数据属性的查看方法

步骤：
- 熟悉数据属性：
  - 抽样查看数据。方法：
    - df.head(n):查看首个(n)行数据
    - df.tail(n)：查看最后(n)行数据
    - df.sample(n)： 随机查看（n）行数据
  - 检查数据基本信息/类型和形状. 方法：
    - df.info: 显示所有数据的类型、索引情况、行列数、各字段数据类型、内存占用等。注意：Series不支持
    - df.dtype: 返回每个字段的数据类型及DataFrame整体的类型
    - df.shape:  返回一个set（行数，列数）。注意：不包含索引。Series结构：列数为空
- 数据检测 （Sanity Check）
  - df.describe()： 返回df数据的统计信息（表格形式），每一行对应一个统计指标，如总数、均值、标准差、最小值、四分位数、最大值等。

In [67]:
# 抽样查看数据
display(df.head(3))      # 查看前3行
display(df.tail(3))      # 查看最后3行
display(df.sample(2))    # 随机查看2行

           state    area       pop     density
abbr
CA    California  423967  38332521   90.413926
TX         Texas  695662  26448193   38.018740
NY      New York  141297  19651127  139.076746

         state    area       pop     density
abbr
NY    New York  141297  19651127  139.076746
FL     Florida  170312  19552860  114.806121
IL    Illinois  149995  12882135   85.883763

           state    area       pop     density
abbr
CA    California  423967  38332521   90.413926
NY      New York  141297  19651127  139.076746

In [68]:
# 检查数据基本信息/类型和形状
df.info()                # 显示数据类型、索引、行列数等
display(df.dtypes)       # 返回每个字段的数据类型
print(df.shape)          # 返回(行数, 列数)

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to IL
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   state    5 non-null      object
 1   area     5 non-null      int64
 2   pop      5 non-null      int64
 3   density  5 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 200.0+ bytes

state       object
area         int64
pop          int64
density    float64
dtype: object

(5, 4)

In [ ]:
# 数据检测（Sanity Check）
disf.describe())   # 返回统计信息play(d

                area           pop     density
count       5.000000  5.000000e+00    5.000000
mean   316246.600000  2.337337e+07   93.639859
std    242437.411951  9.640386e+06   37.672251
min    141297.000000  1.288214e+07   38.018740
25%    149995.000000  1.955286e+07   85.883763
50%    170312.000000  1.965113e+07   90.413926
75%    423967.000000  2.644819e+07  114.806121
max    695662.000000  3.833252e+07  139.076746

### 以列为对象，对数据表中的数据进行数学运算。

In [70]:
# 1. 新增一列：总人口数增加1000
df['pop_plus_1000'] = df['pop'] + 1000

# 2. 新增一列：面积减少10%
df['area_minus_10pct'] = df['area'] * 0.9

# 3. 新增一列：人口密度翻倍
df['density_double'] = df['density'] * 2

# 4. 新增一列：人口除以面积的整数部分
df['pop_div_area_int'] = df['pop'] // df['area']

# 5. 新增一列：人口对面积取余
df['pop_mod_area'] = df['pop'] % df['area']

# 6. 新增一列：人口密度的平方
df['density_pow2'] = df['density'] ** 2

# 7. 新增一列：人口密度大于100的布尔值
df['density_gt_100'] = df['density'] > 100

# 8. 新增一列：人口密度小于50或大于200
df['density_outlier'] = (df['density'] < 50) | (df['density'] > 200)

# 9. 新增一列：人口密度等于最大密度
df['density_is_max'] = df['density'] == df['density'].max()

# 10. 新增一列：人口密度排名（降序）
df['density_rank'] = df['density'].rank(ascending=False, method='min').astype(int)

display(df.head())

,state,area,pop,density,pop_plus_1000,area_minus_10pct,density_double,pop_div_area_int,pop_mod_area,density_pow2,density_gt_100,density_outlier,density_is_max,density_rank
abbr,,,,,,,,,,,,,,
CA,California,423967,38332521,90.413926,38333521,381570.3,180.827852,90,175491,8174.678030,False,False,False,3
TX,Texas,695662,26448193,38.018740,26449193,626095.8,76.037481,38,13037,1445.424623,False,True,False,5
NY,New York,141297,19651127,139.076746,19652127,127167.3,278.153492,139,10844,19342.341318,True,False,True,1
FL,Florida,170312,19552860,114.806121,19553860,153280.8,229.612241,114,137292,13180.445312,True,False,False,2
IL,Illinois,149995,12882135,85.883763,12883135,134995.5,171.767526,85,132560,7376.020711,False,False,False,4

### 数据表的排序 按索引或字段排序

In [71]:
# 按索引字母升序排序
df_sorted = df.sort_index(ascending=True)
display(df_sorted)

,state,area,pop,density,pop_plus_1000,area_minus_10pct,density_double,pop_div_area_int,pop_mod_area,density_pow2,density_gt_100,density_outlier,density_is_max,density_rank
abbr,,,,,,,,,,,,,,
CA,California,423967,38332521,90.413926,38333521,381570.3,180.827852,90,175491,8174.678030,False,False,False,3
FL,Florida,170312,19552860,114.806121,19553860,153280.8,229.612241,114,137292,13180.445312,True,False,False,2
IL,Illinois,149995,12882135,85.883763,12883135,134995.5,171.767526,85,132560,7376.020711,False,False,False,4
NY,New York,141297,19651127,139.076746,19652127,127167.3,278.153492,139,10844,19342.341318,True,False,True,1
TX,Texas,695662,26448193,38.018740,26449193,626095.8,76.037481,38,13037,1445.424623,False,True,False,5

In [ ]:
#按照人口字段排序
df_sorted_by_pop = df.sort_values(by='pop', ascending=True)
display(df_sorted_by_pop)

,state,area,pop,density,pop_plus_1000,area_minus_10pct,density_double,pop_div_area_int,pop_mod_area,density_pow2,density_gt_100,density_outlier,density_is_max,density_rank
abbr,,,,,,,,,,,,,,
IL,Illinois,149995,12882135,85.883763,12883135,134995.5,171.767526,85,132560,7376.020711,False,False,False,4
FL,Florida,170312,19552860,114.806121,19553860,153280.8,229.612241,114,137292,13180.445312,True,False,False,2
NY,New York,141297,19651127,139.076746,19652127,127167.3,278.153492,139,10844,19342.341318,True,False,True,1
TX,Texas,695662,26448193,38.018740,26449193,626095.8,76.037481,38,13037,1445.424623,False,True,False,5
CA,California,423967,38332521,90.413926,38333521,381570.3,180.827852,90,175491,8174.678030,False,False,False,3

# The following table lists Python operators and their equivalent Pandas object methods:

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |

#### 练习

## 2. 数据预处理 Data Preparation  <a id="2"></a>

好数据的评估指标：准确，完整，一致，可调用，合规

必要流程：
- 数据清洗（Data Cleaning）
  - 缺失值
  - （异常值发现和处理）
- 数据准备：  
- 数据转换
- 数据调整

### 2.1 掌握Pandas索引

#### 2.1.1 Pandas数据的索引操作

基础知识点和必备技能：
 - 了解Pandas索引的种类
 - 索引的构建（包含）
 - 索引的重建（保留/覆盖原索引）

#### 2.1.2 通过操作索引来操作Pandas数据

基础知识点和必备技能：
- 用索引来筛选数据

## 3. 数据分析和探索，建模  Data Analysis & Data  Mining，Modelling <a id="3"></a>

方法：
1. 统计学分析
   1. 发现和处理异常值
2. 行业领域分析
3. 分析结果可视化

### 基于数据的建模

我们可以思考如何从现有的数据中提取更具有价值的信息，通常的方法就是建立一些自己的观点=模型，再验证。

在第一个Python学习项目中，我们可以思考如下：
- 建立用户年龄和购买关系的模型：
  - 假设：销售额和用户年龄相关 → 建立一个用户年龄和销售额的关系模型 →通过数学解析或图解法求得该关系 → 验证自己的假设是否属实（证实或证伪）
- 建立一个用户年龄和区域的关系： → 自己尝试
  - 假设：不同区域的人群拥有某个显性的购买趋向 → 建立一个用户年龄和地域的关系模型 → 通过数学解析或图解法求得对应关系 → 验证假设

### 数据可视化

了解和学习使用画图专业户matplotlib

## 4. 模型评估 Model Evaluation <a id="4"></a>

## 5. 业务理解/知识深化和提升  <a id="5"></a> 

总结：
项目目标: 通过实际案例学习和熟悉Pandas的读取最常见数据类型的方法，基础操作。

练习步骤：


学习体会和反馈？

如何玩转Pandas的Index？
心得体会： 
- 一般的常识：功能越广泛， 操作设计就会越复杂。 
- Index的设计就很贴切
- 很多人在使用过程中，往往会对变化多端的用法和各种各样的规矩产生疑惑（比如衍生型的索引使用）
- 学习复杂的方法，切忌死记硬背，效果最差。最有效的方法是搞清楚它的设计逻辑和相关的主要注意点。 如同展开逆向工程来理解造物主的想法。
- 对于复杂的筛选方法的困惑，原因或主要在于理不清筛选条件的适用范围和返回值